""" Module containing CMIP model information
"""

models = {
    "ACCESS-CM2": {
        "model": "ACCESS-CM2",
        "piControl": {
            "r": 1,
            "i": 1,
            "p": 1,
            "f": 1,
        },
        "1pctCO2": {
            "r": 1,
            "i": 1,
            "p": 1,
            "f": 1,
        },
        "abrupt-4xCO2": {
            "r": 1,
            "i": 1,
            "p": 1,
            "f": 1,
        },
        "historical": {
            "r": 2,
            "i": 1,
            "p": 1,
            "f": 1,
        },
    },
    "ACCESS-ESM1-5": {
        "model": "ACCESS-ESM1-5",
        "piControl": {
            "r": 1,
            "i": 1,
            "p": 1,
            "f": 1,
        },
        "1pctCO2": {
            "r": 1,
            "i": 1,
            "p": 1,
            "f": 1,
        },
        "abrupt-4xCO2": {
            "r": 1,
            "i": 1,
            "p": 1,
            "f": 1,
        },
        "historical": {
            "r": 3,
            "i": 1,
            "p": 1,
            "f": 1,
        },
    },
    "ACCESS1-0": {
        "model": "ACCESS1-0",
        "piControl": {
            "r": 1,
            "i": 1,
            "p": 1,
            "f": 0,
        },
        "1pctCO2": {
            "r": 1,
            "i": 1,
            "p": 1,
            "f": 0,
        },
        "abrupt-4xCO2": {
            "r": 1,
            "i": 1,
            "p": 1,
            "f": 0,
        },
        "historical": {
            "r": 3,
            "i": 1,
            "p": 1,
            "f": 0,
        },
    },
    "ACCESS1-3": {
        "model": "ACCESS1-3",
        "piControl": {
            "r": 1,
            "i": 1,
            "p": 1,
            "f": 0,
        },
        "1pctCO2": {
            "r": 1,
            "i": 1,
            "p": 1,
            "f": 0,
        },
        "abrupt-4xCO2": {
            "r": 1,
            "i": 1,
            "p": 1,
            "f": 0,
        },
        "historical": {
            "r": 1,
            "i": 1,
            "p": 1,
            "f": 0,
        },
    },
    "BCC-CSM2-MR": {
        "model": "BCC-CSM2-MR",
        "piControl": {
            "r": 1,
            "i": 1,
            "p": 1,
            "f": 1,
        },
        "1pctCO2": {
            "r": 1,
            "i": 1,
            "p": 1,
            "f": 1,
        },
        "abrupt-4xCO2": {
            "r": 1,
            "i": 1,
            "p": 1,
            "f": 1,
        },
        "historical": {
            "r": 1,
            "i": 1,
            "p": 1,
            "f": 1,
        },
    },
    "BNU-ESM": {
        "model": "BNU-ESM",
        "piControl": {
            "r": 1,
            "i": 1,
            "p": 1,
            "f": 0,
        },
        "1pctCO2": {
            "r": 1,
            "i": 1,
            "p": 1,
            "f": 0,
        },
        "abrupt-4xCO2": {
            "r": 1,
            "i": 1,
            "p": 1,
            "f": 0,
        },
        "historical": {
            "r": 1,
            "i": 1,
            "p": 1,
            "f": 0,
        },
    },
    "CAMS-CSM1-0": {
        "model": "CAMS-CSM1-0",
        "piControl": {
            "r": 1,
            "i": 1,
            "p": 1,
            "f": 1,
        },
        "1pctCO2": {
            "r": 2,
            "i": 1,
            "p": 1,
            "f": 1,
        },
        "abrupt-4xCO2": {
            "r": 2,
            "i": 1,
            "p": 1,
            "f": 1,
        },
        "historical": {
            "r": 1,
            "i": 1,
            "p": 1,
            "f": 2,
        },
    },
    "CCSM4": {
        "model": "CCSM4",
        "piControl": {
            "r": 1,
            "i": 1,
            "p": 1,
            "f": 0,
        },
        "1pctCO2": {
            "r": 1,
            "i": 1,
            "p": 1,
            "f": 0,
        },
        "abrupt-4xCO2": {
            "r": 1,
            "i": 1,
            "p": 1,
            "f": 0,
        },
        "historical": {
            "r": 1,
            "i": 2,
            "p": 1,
            "f": 0,
        },
    },
    "CESM2-FV2": {
        "model": "CESM2-FV2",
        "piControl": {
            "r": 1,
            "i": 1,
            "p": 1,
            "f": 1,
        },
        "1pctCO2": {
            "r": 1,
            "i": 1,
            "p": 1,
            "f": 1,
        },
        "abrupt-4xCO2": {
            "r": 1,
            "i": 1,
            "p": 1,
            "f": 1,
        },
        "historical": {
            "r": [2, 3, ],
            "i": 1,
            "p": 1,
            "f": 1,
        },
    },
    "CESM2-WACCM-FV2": {
        "model": "CESM2-WACCM-FV2",
        "piControl": {
            "r": 1,
            "i": 1,
            "p": 1,
            "f": 1,
        },
        "1pctCO2": {
            "r": 1,
            "i": 1,
            "p": 1,
            "f": 1,
        },
        "abrupt-4xCO2": {
            "r": 1,
            "i": 1,
            "p": 1,
            "f": 1,
        },
        "historical": {
            "r": [2, 3, ],
            "i": 1,
            "p": 1,
            "f": 1,
        },
    },
    "CESM2-WACCM": {
        "model": "CESM2-WACCM",
        "piControl": {
            "r": 1,
            "i": 1,
            "p": 1,
            "f": 1,
        },
        "1pctCO2": {
            "r": 1,
            "i": 1,
            "p": 1,
            "f": 1,
        },
        "abrupt-4xCO2": {
            "r": 1,
            "i": 1,
            "p": 1,
            "f": 1,
        },
        "historical": {
            "r": [1, 2, 3, ],
            "i": 1,
            "p": 1,
            "f": 1,
        },
    },
    "CESM2": {
        "model": "CESM2",
        "piControl": {
            "r": 1,
            "i": 1,
            "p": 1,
            "f": 1,
        },
        "1pctCO2": {
            "r": 1,
            "i": 1,
            "p": 1,
            "f": 1,
        },
        "abrupt-4xCO2": {
            "r": 1,
            "i": 1,
            "p": 1,
            "f": 1,
        },
        "historical": {
            "r": 11,
            "i": 1,
            "p": 1,
            "f": 1,
        },
    },
    "CMCC-CM2-SR5": {
        "model": "CMCC-CM2-SR5",
        "piControl": {
            "r": 1,
            "i": 1,
            "p": 1,
            "f": 1,
        },
        "1pctCO2": {
            "r": 1,
            "i": 1,
            "p": 1,
            "f": 1,
        },
        "abrupt-4xCO2": {
            "r": 1,
            "i": 1,
            "p": 1,
            "f": 1,
        },
        "historical": {
            "r": 1,
            "i": 1,
            "p": 1,
            "f": 1,
        },
    },
    "CNRM-CM5-2": {
        "model": "CNRM-CM5-2",
        "piControl": {
            "r": 1,
            "i": 1,
            "p": 1,
            "f": 0,
        },
        "1pctCO2": {
            "r": 1,
            "i": 1,
            "p": 2,
            "f": 0,
        },
        "abrupt-4xCO2": {
            "r": 1,
            "i": 1,
            "p": 1,
            "f": 0,
        },
        "historical": {
            "r": 1,
            "i": 1,
            "p": 1,
            "f": 0,
        },
    },
    "CNRM-CM5": {
        "model": "CNRM-CM5",
        "piControl": {
            "r": 1,
            "i": 1,
            "p": 1,
            "f": 0,
        },
        "1pctCO2": {
            "r": 1,
            "i": 1,
            "p": 2,
            "f": 0,
        },
        "abrupt-4xCO2": {
            "r": 1,
            "i": 1,
            "p": 1,
            "f": 0,
        },
        "historical": {
            "r": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, ],
            "i": 1,
            "p": 1,
            "f": 0,
        },
    },
    "CNRM-CM6-1-HR": {
        "model": "CNRM-CM6-1-HR",
        "piControl": {
            "r": 1,
            "i": 1,
            "p": 1,
            "f": 2,
        },
        "1pctCO2": {
            "r": 1,
            "i": 1,
            "p": 1,
            "f": 2,
        },
        "abrupt-4xCO2": {
            "r": 1,
            "i": 1,
            "p": 1,
            "f": 2,
        },
        "historical": {
            "r": 1,
            "i": 1,
            "p": 1,
            "f": 2,
        },
    },
    "CNRM-ESM2-1": {
        "model": "CNRM-ESM2-1",
        "piControl": {
            "r": 1,
            "i": 1,
            "p": 1,
            "f": 2,
        },
        "1pctCO2": {
            "r": 7,
            "i": 1,
            "p": 1,
            "f": 2,
        },
        "abrupt-4xCO2": {
            "r": 3,
            "i": 1,
            "p": 1,
            "f": 2,
        },
        "historical": {
            "r": [7, 8, 9, 10, ],
            "i": 1,
            "p": 1,
            "f": 2,
        },
    },
    "CanESM2": {
        "model": "CanESM2",
        "piControl": {
            "r": 1,
            "i": 1,
            "p": 1,
            "f": 0,
        },
        "1pctCO2": {
            "r": 1,
            "i": 1,
            "p": 1,
            "f": 0,
        },
        "abrupt-4xCO2": {
            "r": 1,
            "i": 1,
            "p": 1,
            "f": 0,
        },
        "historical": {
            "r": [1, 2, 3, 4, 5, ],
            "i": 1,
            "p": 1,
            "f": 0,
        },
    },
    "CanESM5_a": {
        "model": "CanESM5",
        "piControl": {
            "r": 1,
            "i": 1,
            "p": 1,
            "f": 1,
        },
        "1pctCO2": {
            "r": 1,
            "i": 1,
            "p": 1,
            "f": 1,
        },
        "abrupt-4xCO2": {
            "r": 1,
            "i": 1,
            "p": 1,
            "f": 1,
        },
        "historical": {
            "r": 1,
            "i": 1,
            "p": 1,
            "f": 1,
        },
    },
    "CanESM5_b": {
        "model": "CanESM5",
        "piControl": {
            "r": 1,
            "i": 1,
            "p": 2,
            "f": 1,
        },
        "1pctCO2": {
            "r": 1,
            "i": 1,
            "p": 2,
            "f": 1,
        },
        "abrupt-4xCO2": {
            "r": 1,
            "i": 1,
            "p": 2,
            "f": 1,
        },
        "historical": {
            "r": 1,
            "i": 1,
            "p": 2,
            "f": 1,
        },
    },
    "FGOALS-g2": {
        "model": "FGOALS-g2",
        "piControl": {
            "r": 1,
            "i": 1,
            "p": 1,
            "f": 0,
        },
        "1pctCO2": {
            "r": 1,
            "i": 1,
            "p": 1,
            "f": 0,
        },
        "abrupt-4xCO2": {
            "r": 1,
            "i": 1,
            "p": 1,
            "f": 0,
        },
        "historical": {
            "r": [1, 2, 3, 4, 5, ],
            "i": 1,
            "p": 1,
            "f": 0,
        },
    },
    "FGOALS-g3": {
        "model": "FGOALS-g3",
        "piControl": {
            "r": 1,
            "i": 1,
            "p": 1,
            "f": 1,
        },
        "1pctCO2": {
            "r": 1,
            "i": 1,
            "p": 1,
            "f": 1,
        },
        "abrupt-4xCO2": {
            "r": 1,
            "i": 1,
            "p": 1,
            "f": 1,
        },
        "historical": {
            "r": 1,
            "i": 1,
            "p": 1,
            "f": 1,
        },
    },
    "GFDL-CM3": {
        "model": "GFDL-CM3",
        "piControl": {
            "r": 1,
            "i": 1,
            "p": 1,
            "f": 0,
        },
        "1pctCO2": {
            "r": 1,
            "i": 1,
            "p": 1,
            "f": 0,
        },
        "abrupt-4xCO2": {
            "r": 1,
            "i": 1,
            "p": 1,
            "f": 0,
        },
        "historical": {
            "r": [1, 2, 3, 4, 5],
            "i": 1,
            "p": 1,
            "f": 0,
        },
    },
    "GFDL-CM4": {
        "model": "GFDL-CM4",
        "piControl": {
            "r": 1,
            "i": 1,
            "p": 1,
            "f": 1,
        },
        "1pctCO2": {
            "r": 1,
            "i": 1,
            "p": 1,
            "f": 1,
        },
        "abrupt-4xCO2": {
            "r": 1,
            "i": 1,
            "p": 1,
            "f": 1,
        },
        "historical": {
            "r": 1,
            "i": 1,
            "p": 1,
            "f": 1,
        },
    },
    "GFDL-ESM2G": {
        "model": "GFDL-ESM2G",
        "piControl": {
            "r": 1,
            "i": 1,
            "p": 1,
            "f": 0,
        },
        "1pctCO2": {
            "r": 1,
            "i": 1,
            "p": 1,
            "f": 0,
        },
        "abrupt-4xCO2": {
            "r": 1,
            "i": 1,
            "p": 1,
            "f": 0,
        },
        "historical": {
            "r": 1,
            "i": 1,
            "p": 1,
            "f": 0,
        },
    },
    "GFDL-ESM2M": {
        "model": "GFDL-ESM2M",
        "piControl": {
            "r": 1,
            "i": 1,
            "p": 1,
            "f": 0,
        },
        "1pctCO2": {
            "r": 1,
            "i": 1,
            "p": 1,
            "f": 0,
        },
        "abrupt-4xCO2": {
            "r": 1,
            "i": 1,
            "p": 1,
            "f": 0,
        },
        "historical": {
            "r": 1,
            "i": 1,
            "p": 1,
            "f": 0,
        },
    },
    "GFDL-ESM4": {
        "model": "GFDL-ESM4",
        "piControl": {
            "r": 1,
            "i": 1,
            "p": 1,
            "f": 1,
        },
        "1pctCO2": {
            "r": 1,
            "i": 1,
            "p": 1,
            "f": 1,
        },
        "abrupt-4xCO2": {
            "r": 1,
            "i": 1,
            "p": 1,
            "f": 1,
        },
        "historical": {
            "r": 1,
            "i": 1,
            "p": 1,
            "f": 1,
        },
    },
    "GISS-E2-1-G": {
        "model": "GISS-E2-1-G",
        "piControl": {
            "r": 2,
            "i": 1,
            "p": 1,
            "f": 1,
        },
        "1pctCO2": {
            "r": 1,
            "i": 1,
            "p": 5,
            "f": 1,
        },
        "abrupt-4xCO2": {
            "r": 1,
            "i": 1,
            "p": 1,
            "f": 3,
        },
        "historical": {
            "r": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, ],
            "i": 1,
            "p": 1,
            "f": 2,
        },
    },
    "GISS-E2-1-H": {
        "model": "GISS-E2-1-H",
        "piControl": {
            "r": 1,
            "i": 1,
            "p": 3,
            "f": 1,
        },
        "1pctCO2": {
            "r": 1,
            "i": 1,
            "p": 1,
            "f": 1,
        },
        "abrupt-4xCO2": {
            "r": 1,
            "i": 1,
            "p": 1,
            "f": 1,
        },
        "historical": {
            "r": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, ],
            "i": 1,
            "p": 1,
            "f": 1,
        },
    },
    "GISS-E2-H_a": {
        "model": "GISS-E2-H",
        "piControl": {
            "r": 1,
            "i": 1,
            "p": 1,
            "f": 0,
        },
        "1pctCO2": {
            "r": 1,
            "i": 1,
            "p": 2,
            "f": 0,
        },
        "abrupt-4xCO2": {
            "r": 1,
            "i": 1,
            "p": 2,
            "f": 0,
        },
        "historical": {
            "r": [1, 2, 3, 4, 5, 6, ],
            "i": 1,
            "p": 1,
            "f": 0,
        },
    },
    "GISS-E2-H_b": {
        "model": "GISS-E2-H",
        "piControl": {
            "r": 1,
            "i": 1,
            "p": 2,
            "f": 0,
        },
        "1pctCO2": {
            "r": 1,
            "i": 1,
            "p": 2,
            "f": 0,
        },
        "abrupt-4xCO2": {
            "r": 1,
            "i": 1,
            "p": 2,
            "f": 0,
        },
        "historical": {
            "r": [1, 2, 3, 4, 5, 6, ],
            "i": 1,
            "p": 2,
            "f": 0,
        },
    },
    "GISS-E2-H_c": {
        "model": "GISS-E2-H",
        "piControl": {
            "r": 1,
            "i": 1,
            "p": 3,
            "f": 0,
        },
        "1pctCO2": {
            "r": 1,
            "i": 1,
            "p": 2,
            "f": 0,
        },
        "abrupt-4xCO2": {
            "r": 1,
            "i": 1,
            "p": 2,
            "f": 0,
        },
        "historical": {
            "r": [1, 2, 3, 4, 5, 6, ],
            "i": 1,
            "p": 3,
            "f": 0,
        },
    },
    "INM-CM5-0": {
        "model": "INM-CM5-0",
        "piControl": {
            "r": 1,
            "i": 1,
            "p": 1,
            "f": 1,
        },
        "1pctCO2": {
            "r": 1,
            "i": 1,
            "p": 1,
            "f": 1,
        },
        "abrupt-4xCO2": {
            "r": 1,
            "i": 1,
            "p": 1,
            "f": 1,
        },
        "historical": {
            "r": 11,
            "i": 1,
            "p": 1,
            "f": 1,
        },
    },
    "IPSL-CM5A-MR": {
        "model": "IPSL-CM5A-MR",
        "piControl": {
            "r": 1,
            "i": 1,
            "p": 1,
            "f": 0,
        },
        "1pctCO2": {
            "r": 1,
            "i": 1,
            "p": 1,
            "f": 0,
        },
        "abrupt-4xCO2": {
            "r": 1,
            "i": 1,
            "p": 1,
            "f": 0,
        },
        "historical": {
            "r": 3,
            "i": 1,
            "p": 1,
            "f": 0,
        },
    },
    "IPSL-CM5B-LR": {
        "model": "IPSL-CM5B-LR",
        "piControl": {
            "r": 1,
            "i": 1,
            "p": 1,
            "f": 0,
        },
        "1pctCO2": {
            "r": 1,
            "i": 1,
            "p": 1,
            "f": 0,
        },
        "abrupt-4xCO2": {
            "r": 1,
            "i": 1,
            "p": 1,
            "f": 0,
        },
        "historical": {
            "r": 1,
            "i": 1,
            "p": 1,
            "f": 0,
        },
    },
    "IPSL-CM6A-LR": {
        "model": "IPSL-CM6A-LR",
        "piControl": {
            "r": 1,
            "i": 2,
            "p": 1,
            "f": 1,
        },
        "1pctCO2": {
            "r": 1,
            "i": 1,
            "p": 1,
            "f": 1,
        },
        "abrupt-4xCO2": {
            "r": 1,
            "i": 1,
            "p": 1,
            "f": 1,
        },
        "historical": {
            "r": 32,
            "i": 1,
            "p": 1,
            "f": 1,
        },
    },
    "MIROC-ES2L": {
        "model": "MIROC-ES2L",
        "piControl": {
            "r": 1,
            "i": 1,
            "p": 1,
            "f": 2,
        },
        "1pctCO2": {
            "r": 1,
            "i": 1,
            "p": 1,
            "f": 2,
        },
        "abrupt-4xCO2": {
            "r": 1,
            "i": 1,
            "p": 1,
            "f": 2,
        },
        "historical": {
            "r": [1, 2, 3, ],
            "i": 1,
            "p": 1,
            "f": 2,
        },
    },
    "MIROC-ESM": {
        "model": "MIROC-ESM",
        "piControl": {
            "r": 1,
            "i": 1,
            "p": 1,
            "f": 0,
        },
        "1pctCO2": {
            "r": 1,
            "i": 1,
            "p": 1,
            "f": 0,
        },
        "abrupt-4xCO2": {
            "r": 1,
            "i": 1,
            "p": 1,
            "f": 0,
        },
        "historical": {
            "r": [1, 2, 3, ],
            "i": 1,
            "p": 1,
            "f": 0,
        },
    },
    "MIROC5": {
        "model": "MIROC5",
        "piControl": {
            "r": 1,
            "i": 1,
            "p": 1,
            "f": 0,
        },
        "1pctCO2": {
            "r": 1,
            "i": 1,
            "p": 1,
            "f": 0,
        },
        "abrupt-4xCO2": {
            "r": 1,
            "i": 1,
            "p": 1,
            "f": 0,
        },
        "historical": {
            "r": 4,
            "i": 1,
            "p": 1,
            "f": 0,
        },
    },
    "MPI-ESM-LR": {
        "model": "MPI-ESM-LR",
        "piControl": {
            "r": 1,
            "i": 1,
            "p": 1,
            "f": 0,
        },
        "1pctCO2": {
            "r": 1,
            "i": 1,
            "p": 1,
            "f": 0,
        },
        "abrupt-4xCO2": {
            "r": 1,
            "i": 1,
            "p": 1,
            "f": 0,
        },
        "historical": {
            "r": [1, 2, 3, ],
            "i": 1,
            "p": 1,
            "f": 0,
        },
    },
    "MPI-ESM-MR": {
        "model": "MPI-ESM-MR",
        "piControl": {
            "r": 1,
            "i": 1,
            "p": 1,
            "f": 0,
        },
        "1pctCO2": {
            "r": 1,
            "i": 1,
            "p": 1,
            "f": 0,
        },
        "abrupt-4xCO2": {
            "r": 1,
            "i": 1,
            "p": 1,
            "f": 0,
        },
        "historical": {
            "r": [1, 2, 3, ],
            "i": 1,
            "p": 1,
            "f": 0,
        },
    },
    "MPI-ESM-P": {
        "model": "MPI-ESM-P",
        "piControl": {
            "r": 1,
            "i": 1,
            "p": 1,
            "f": 0,
        },
        "1pctCO2": {
            "r": 1,
            "i": 1,
            "p": 1,
            "f": 0,
        },
        "abrupt-4xCO2": {
            "r": 1,
            "i": 1,
            "p": 1,
            "f": 0,
        },
        "historical": {
            "r": [1, 2, ],
            "i": 1,
            "p": 1,
            "f": 0,
        },
    },
    "MPI-ESM1-2-HR": {
        "model": "MPI-ESM1-2-HR",
        "piControl": {
            "r": 1,
            "i": 1,
            "p": 1,
            "f": 1,
        },
        "1pctCO2": {
            "r": 1,
            "i": 1,
            "p": 1,
            "f": 1,
        },
        "abrupt-4xCO2": {
            "r": 1,
            "i": 1,
            "p": 1,
            "f": 1,
        },
        "historical": {
            "r": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, ],
            "i": 1,
            "p": 1,
            "f": 1,
        },
    },
    "MPI-ESM1-2-LR": {
        "model": "MPI-ESM1-2-LR",
        "piControl": {
            "r": 2,
            "i": 1,
            "p": 1,
            "f": 1,
        },
        "1pctCO2": {
            "r": 1,
            "i": 1,
            "p": 1,
            "f": 1,
        },
        "abrupt-4xCO2": {
            "r": 1,
            "i": 1,
            "p": 1,
            "f": 1,
        },
        "historical": {
            "r": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, ],
            "i": 1,
            "p": 1,
            "f": 1,
        },
    },
    "MRI-CGCM3": {
        "model": "MRI-CGCM3",
        "piControl": {
            "r": 1,
            "i": 1,
            "p": 1,
            "f": 0,
        },
        "1pctCO2": {
            "r": 1,
            "i": 1,
            "p": 1,
            "f": 0,
        },
        "abrupt-4xCO2": {
            "r": 1,
            "i": 1,
            "p": 1,
            "f": 0,
        },
        "historical": {
            "r": [1, 2, 3, 4, 5, ],
            "i": 1,
            "p": 1,
            "f": 0,
        },
    },
    "NorCPM1": {
        "model": "NorCPM1",
        "piControl": {
            "r": 1,
            "i": 1,
            "p": 1,
            "f": 1,
        },
        "1pctCO2": {
            "r": 1,
            "i": 1,
            "p": 1,
            "f": 1,
        },
        "abrupt-4xCO2": {
            "r": 1,
            "i": 1,
            "p": 1,
            "f": 1,
        },
        "historical": {
            "r": 10,
            "i": 1,
            "p": 1,
            "f": 1,
        },
    },
    "NorESM1-M": {
        "model": "NorESM1-M",
        "piControl": {
            "r": 1,
            "i": 1,
            "p": 1,
            "f": 0,
        },
        "1pctCO2": {
            "r": 1,
            "i": 1,
            "p": 1,
            "f": 0,
        },
        "abrupt-4xCO2": {
            "r": 1,
            "i": 1,
            "p": 1,
            "f": 0,
        },
        "historical": {
            "r": [1, 2, 3, ],
            "i": 1,
            "p": 1,
            "f": 0,
        },
    },
    "NorESM2-MM": {
        "model": "NorESM2-MM",
        "piControl": {
            "r": 1,
            "i": 1,
            "p": 1,
            "f": 1,
        },
        "1pctCO2": {
            "r": 1,
            "i": 1,
            "p": 1,
            "f": 1,
        },
        "abrupt-4xCO2": {
            "r": 1,
            "i": 1,
            "p": 1,
            "f": 1,
        },
        "historical": {
            "r": 1,
            "i": 1,
            "p": 1,
            "f": 1,
        },
    },
    "SAM0-UNICON": {
        "model": "SAM0-UNICON",
        "piControl": {
            "r": 1,
            "i": 1,
            "p": 1,
            "f": 1,
        },
        "1pctCO2": {
            "r": 1,
            "i": 1,
            "p": 1,
            "f": 1,
        },
        "abrupt-4xCO2": {
            "r": 1,
            "i": 1,
            "p": 1,
            "f": 1,
        },
        "historical": {
            "r": 1,
            "i": 1,
            "p": 1,
            "f": 1,
        },
    },
    "TaiESM1": {
        "model": "TaiESM1",
        "piControl": {
            "r": 1,
            "i": 1,
            "p": 1,
            "f": 1,
        },
        "1pctCO2": {
            "r": 1,
            "i": 1,
            "p": 1,
            "f": 1,
        },
        "abrupt-4xCO2": {
            "r": 1,
            "i": 1,
            "p": 1,
            "f": 1,
        },
        "historical": {
            "r": 1,
            "i": 1,
            "p": 1,
            "f": 1,
        },
    },
    "bcc-csm1-1-m": {
        "model": "bcc-csm1-1-m",
        "piControl": {
            "r": 1,
            "i": 1,
            "p": 1,
            "f": 0,
        },
        "1pctCO2": {
            "r": 1,
            "i": 1,
            "p": 1,
            "f": 0,
        },
        "abrupt-4xCO2": {
            "r": 1,
            "i": 1,
            "p": 1,
            "f": 0,
        },
        "historical": {
            "r": [1, 2, 3, ],
            "i": 1,
            "p": 1,
            "f": 0,
        },
    },
    "bcc-csm1-1": {
        "model": "bcc-csm1-1",
        "piControl": {
            "r": 1,
            "i": 1,
            "p": 1,
            "f": 0,
        },
        "1pctCO2": {
            "r": 1,
            "i": 1,
            "p": 1,
            "f": 0,
        },
        "abrupt-4xCO2": {
            "r": 1,
            "i": 1,
            "p": 1,
            "f": 0,
        },
        "historical": {
            "r": [1, 2, 3, ],
            "i": 1,
            "p": 1,
            "f": 0,
        },
    },
    "inmcm4": {
        "model": "inmcm4",
        "piControl": {
            "r": 1,
            "i": 1,
            "p": 1,
            "f": 0,
        },
        "1pctCO2": {
            "r": 1,
            "i": 1,
            "p": 1,
            "f": 0,
        },
        "abrupt-4xCO2": {
            "r": 1,
            "i": 1,
            "p": 1,
            "f": 0,
        },
        "historical": {
            "r": 1,
            "i": 1,
            "p": 1,
            "f": 0,
        },
    },
}